<a href="https://colab.research.google.com/github/Jishna-tp/Learn.py/blob/main/TASK_17.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1. Create a DataFrame by passing a random numpy array,with a datetie index and labelled columns.and display its,
     - Head
     - Tail
     - Index 
     - Columns
     - Values
     - statistics


In [21]:
#please type your answer below this line.
import numpy as np
import pandas as pd
datetie = pd.date_range('2021-08-24',periods=4)
df = pd.DataFrame(np.random.randn(4,4), index=datetie, columns=list('ABCD'))
print("Head:\n", df.head())
print("Tail:\n", df.tail())
print("Index:\n", df.index)
print("Columns:\n", df.columns)
print("Values:\n", df.values)
print("Statistics:\n", df.describe(include='all'))

Head:
                    A         B         C         D
2021-08-24 -1.108542  0.486055  0.948791 -1.209341
2021-08-25 -0.346789 -0.392075  0.136607 -0.811241
2021-08-26  0.502972  1.527944 -0.453552  0.435765
2021-08-27 -0.093899  1.050478 -1.736069 -0.477925
Tail:
                    A         B         C         D
2021-08-24 -1.108542  0.486055  0.948791 -1.209341
2021-08-25 -0.346789 -0.392075  0.136607 -0.811241
2021-08-26  0.502972  1.527944 -0.453552  0.435765
2021-08-27 -0.093899  1.050478 -1.736069 -0.477925
Index:
 DatetimeIndex(['2021-08-24', '2021-08-25', '2021-08-26', '2021-08-27'], dtype='datetime64[ns]', freq='D')
Columns:
 Index(['A', 'B', 'C', 'D'], dtype='object')
Values:
 [[-1.1085418   0.48605548  0.94879092 -1.20934112]
 [-0.3467895  -0.39207461  0.13660678 -0.81124099]
 [ 0.50297199  1.52794385 -0.45355152  0.43576513]
 [-0.09389904  1.05047788 -1.73606946 -0.47792502]]
Statistics:
               A         B         C         D
count  4.000000  4.000000  4.000000

2. Use the above table and,
      - find transpose of your data.
      - sort the index in the descending order of the date.

In [25]:
#please provide your answer below this line.
print("Transpose\n", df.transpose())
print("Sorted in Descending Order\n", df.sort_index(ascending=False))

Transpose
    2021-08-24  2021-08-25  2021-08-26  2021-08-27
A   -1.108542   -0.346789    0.502972   -0.093899
B    0.486055   -0.392075    1.527944    1.050478
C    0.948791    0.136607   -0.453552   -1.736069
D   -1.209341   -0.811241    0.435765   -0.477925
Sorted in Descending Order
                    A         B         C         D
2021-08-27 -0.093899  1.050478 -1.736069 -0.477925
2021-08-26  0.502972  1.527944 -0.453552  0.435765
2021-08-25 -0.346789 -0.392075  0.136607 -0.811241
2021-08-24 -1.108542  0.486055  0.948791 -1.209341
